databases:
  - name: myproject       # ⚠️ يجب أن يتطابق مع اسم الخدمة في لوحة Render
    databaseName: myproject_exii  # اسم قاعدة البيانات الداخلي
    user: root            # اسم المستخدم الذي اخترته عند الإنشاء
    plan: free            # الخطة المجانية

services:
  - type: web
    name: bonus
    runtime: docker
    buildCommand: "./docker-build.sh"
    startCommand: "apache2-foreground"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: "https://bonus-sz5v.onrender.com"  
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: myproject  # ⚠️ يشير إلى اسم الخدمة (وليس اسم DB)
          property: host
      - key: DB_PORT
        fromDatabase:
          name: myproject
          property: port
      - key: DB_DATABASE
        value: "myproject_exii"  # ⚠️ هنا نستخدم اسم DB الفعلي مباشرة
      - key: DB_USERNAME
        fromDatabase:
          name: myproject
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: myproject
          property: password
    plan: free