services:
  - type: web
    name:  bonus  # يمكنك تغيير الاسم
    runtime: docker    # ⚠️ مهم: اختر Docker
    buildCommand: "./docker-build.sh"  # سننشئ هذا الملف
    startCommand: "apache2-foreground"  # تشغيل Apache
    envVars:
      - key: APP_ENV
        value: production
        - key: APP_DEBUG
        value: false